version: '3'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha_123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: rote_db
      MYSQL_PASSWORD: senha_123
    networks:
      - public

  node:
    image: node:12
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_URL: mysql://rote_db:senha_123@db/mydatabase
      JWT_SECRET: xxxxxxxx
      ADMIN_EMAIL: admin@db
      ADMIN_PASSWORD: changeme
    volumes:
      - ./:/home/node/app
    expose:
      - 8080
    ports:
      - 80:8080
    command: bash -c 'rm -rf node_modules && npm install && npm start'
    depends_on:
      - db
    networks:
      - public

networks:
  public:
    internal: false
  private:
    internal: true
